Prgm1: main.o assign.o sort.o print.o
	gcc -o Prgm1 main.o assign.o sort.o print.o

main.o: main.c 
		gcc -c -Wall main.c

assign.o: assign.c
		gcc -c -Wall assign.c

sort.o: sort.c
		gcc -c -Wall sort.c

print.o: print.c
		gcc -c -Wall print.c

